import mongoose, { Schema, Document } from "mongoose";

export interface IConsent extends Document {
  id: UUID;
  name: string;
  consentUrl: string;
  createdAt: Date;
  version: number;
}

const ConsentSchema: Schema = new Schema({
  // The id of the target, generated by api
  id: { type: UUID },

  // A human readable name of the consent we are granting to the user. Required field.
  name: { type: String, required: true },

  // The url. Required field
  consentUrl: { type: String, required: true },

  createdAt: { type: Date },

  version: { type: Number },
  // owner: { type: Schema.Types.ObjectId, required: true }
});

export default mongoose.model<IConsent>("Consent", ConsentSchema);
